### ISSUE TITLE
Action buttons not appearing in teams message

### ISSUE THREAD

**Issue by nofarius** [amrfarid140/bitrise-step-microsoft-teams-integration#2]
Firstly, thanks for creating this bitrise step!

I noticed in the code that when the message is posted to MS Teams that there should be "Go to Repo" and "Go to Build" buttons.
```go
...
goToRepoActionCard := ActionCard{}
goToRepoActionCard.Type = "ActionCard"
goToRepoActionCard.Name = "Go To Repo"
goToRepoActionCardAction := Action{}
goToRepoActionCardAction.Type = "HttpGet"
goToRepoActionCardAction.Name = "Go To Repo"
goToRepoActionCardAction.Target = cfg.RepoURL

goToBuildActionCard := ActionCard{}
goToBuildActionCard.Type = "ActionCard"
goToBuildActionCard.Name = "Go To Build"
goToBuildActionCardAction := Action{}
goToBuildActionCardAction.Type = "HttpGet"
goToBuildActionCardAction.Name = "Go To Build"
goToBuildActionCardAction.Target = cfg.BuildURL
...
```

Neither of those buttons appear in the message in teams
![image](https://user-images.githubusercontent.com/12933462/41573063-8562d456-73ad-11e8-8f74-c5092ee3d2de.png)

Is there something I'm missing? Or is this an issue with this step?

**Comment by amrfarid140** [comment]
Hey,

Yeah you are not missing anything. It's a current issue with step.

**Comment by ThiagoFacchini** [comment]
I bumped into the same issue....

Any progress?

**Comment by StNebel** [comment]
I think its not the current code on bitrise .. your can use this one
```
"potentialAction": [{
      "@type": "OpenUri",
      "name": "Go To Build",
      "targets": [{
        "os": "default",
        "uri": ENV['APPCENTER_APP_URL']
      }]
    }]
```

**Comment by ghost** [comment]
I think its not the current code on bitrise .. your can use this one

```
"potentialAction": [{
      "@type": "OpenUri",
      "name": "Go To Build",
      "targets": [{
        "os": "default",
        "uri": ENV['URL']
      }]
    }]
```

**Comment by amrfarid140** [comment]
Hey @StNebel , I am not using bitrise or Teams right now, feel free to make a PR and I will merge it in.

I can also transfer ownership of this Repo to anyone interesting in maintaining the step. Let me know if you want that.

**Comment by jamieastley** [comment]
@amrfarid140 I'm interested in maintaining the step.. I was going to PR some additional input options anyway to satisfy the other open issue as I needed that too.

**Comment by amrfarid140** [comment]
Hey @jamie1192 , Sure I will add you as a maintainer.

**Comment by jamieastley** [comment]
hey @nofarius , in the off chance you're still desiring this to be fixed after all this time, I currently have a fix in progress, branched on [fix/uri-actions](https://github.com/amrfarid140/bitrise-step-microsoft-teams-integration/tree/fix/uri-actions).

I'm hoping to merge and update the step in the next few days or so.
