### ISSUE TITLE
Request for custom text field on notification panel

### ISSUE THREAD

**Issue by kimrtaylor** [amrfarid140/bitrise-step-microsoft-teams-integration#3]
First of all thanks a lot for creating this bitrise step, my team uses it everyday! 

My request is for a custom text field to be added on the notification panel in MS Teams, the value of which can be set in bitrise. This would allow users to customise the notification panel to their own needs and even set the value to existing environment variables from bitrise e.g. a custom URL. This therefore adds a lot of value with quite a simple change.

Thanks again and keep up the great work!

**Comment by jamieastley** [comment]
hey @kimrtaylor, it's been a while but incase you're still wanting this functionality, I've taken over maintaining this Bitrise step and will be adding additional field functionality in the next step update to close this 🙂

**Comment by kimrtaylor** [comment]
That's brilliant news, thank you for the response @jamie1192. I'll let my old team know 😄

**Comment by jamieastley** [comment]
@kimrtaylor, this is finally done and is pending PR over at the [Steplib repository](https://github.com/bitrise-io/bitrise-steplib/pull/2873), so your old team will be able to update to 1.2.0 once it's merged 🙂
