### ISSUE TITLE
Make the default "Go To Repo" button dynamic (by default)

### ISSUE THREAD

**Issue by clayellis-cricut** [amrfarid140/bitrise-step-microsoft-teams-integration#33]
Currently, the default Go To Repo button just opens the git repo (e.g. `https://github.com/user/repo.git`). It would be nice if the button would, by default, open the git repo at the git reference used to generate the build (e.g. `https://github.com/user/repo.git/tree/some-branch`).

**Comment by clayellis-cricut** [comment]
This is what I'm thinking:

If repo is GitHub and:
- built from branch: `$GIT_REPOSITORY_URL/tree/<branch>`
- built from commit: `$GIT_REPOSITORY_URL/commit/<commit>`
- built from tag: `$GIT_REPOSITORY_URL/tree/<tag>`

Else:
- default to: `$GIT_REPOSITORY_URL`

I'm not sure what the links would look like for GitLab or Bitbucket but they could also be supported.

**Comment by jamieastley** [comment]
This can already be achieved a few ways:

* Using the `actions` input so as to make the action buttons entirely custom. The downside to this is that it means having to include stringified JSON as the input value, until we're able to capture input values dynamically as an array of objects, which [I requested a while back here.](https://github.com/bitrise-io/go-steputils/issues/23)

* Append the [Bitrise environment variable](https://devcenter.bitrise.io/builds/available-environment-variables/) that returns the active branch name onto `repository_url` step input, as this value is what is used for the default "Go To Repo" button.

**Comment by clayellis-cricut** [comment]
Yeah, the only problem is that each service appears to have different url patterns. Even within GitHub it's different whether it was a branch/tag vs a commit. 

It can definitely be customized, but I think there's an argument for making it the default behavior.

**Comment by clayellis-cricut** [comment]
GitLab:
- branch: `$GIT_REPOSITORY_URL/-/tree/<branch>`
- commit: `$GIT_REPOSITORY_URL/-/commit/<commit>`
- tag: `$GIT_REPOSITORY_URL/-/tags/<tag>`

Bitbucket:
- branch: `$GIT_REPOSITORY_URL/browse?at=refs%2Fheads%2F<branch>`
  - also seeing: `$GIT_REPOSITORY_URL/branch/<branch>` 
- commit: It doesn't look like there is a useful view on Bitbucket for browsing a repo's state at a specific commit, just the changes included in that commit.
- tag: `$GIT_REPOSITORY_URL/browse?at=refs%2Ftags%2F<tag>`

**Comment by jamieastley** [comment]
Yeah, and that's exactly why I figured it was best left to the user to define the URL scheme/handling for this kind of thing rather than trying to cater for Github, Bitbucket and Gitlab all within the one step.

**Comment by clayellis-cricut** [comment]
Makes sense! Yeah, after digging up those url formats I think I came to the same realization: it's just too much responsibility for this step.
